
NOTE: See <<Instructions>>

= {product} Overview

{product} allows you to create a Virtual Application Network, which enables you to connect services across clusters and more.

A {product} VAN consists of a set of sites, with each site being defined in the scope of:

* a cluster namespace
* a cluster
* a machine (skupper-docker, upstream only)

You connect sites using tokens to create a VAN. footnote:[You create a {connector} from one site to another, however traffic can be bidirectional]

You {register} services with a site in order to connect those services to other services ({register}ed with other sites) in a VAN. footnote:[You can {register} a service using either `expose` or `bind` commands.]

Typically, when starting with {product}, you create two {interior-site}s.
As your VAN grows, you typically start creating {edge-site}s.

site types include:

{interior-site} (default):: You can only generate tokens from {interior-site}s. You can have up to 128 {interior-site}s in the VAN.
{edge-site}:: You can connect from {edge-site}s to {interior-site}s and communication can be bi-directional.
While a {edge-site} can have multiple {connector}s, it can have only one active {connection} at any time.
footnote:[Paul Opinion: {edge-site}s are like table rows, {interior-site}s are like table columns. You expect to create many rows, but not as many columns.]

Each site enables a console by default. The console helps you understand the sites and services that form the Virtual Application Network, how are they connected, and historical traffic flow either in terms of sites or services.

To change the behaviour of a site:

Create/list/delete {connector}s:: The sites that can create {connection}s to the site.
Connect/disconnect:: Modify {connection}s, that is, active communications with another site.
Set/unset {local-cluster-site}:: Limit creating {connector}s to your local cluster. You can still create a {connector} to this site from a site in a different cluster.


= Instructions

. Play with the links below to set and unset the default variable values.
. If you want to change something, set variables using *Attributes* tab.
. Share resulting link.


[cols=4]
|===

|Attributes:
|link:./index.html[Reset]
|link:./index.html?edge-site=edge+site&site=site&product=Skupper&interior-site=interior+site&local-cluster-site=local+site&connector=connector&connection=connection&register=register[Upstream]
|link:./index.html?edge-site=edge+site&product=Interconnect+2&interior-site=interior+site&local-cluster-site=local+site&connector=connector&connection=connection&register=register[Downstream]

|Options:
|link:https://github.com/pwright/skupper-vocab[Repo]
|link:https://github.com/pwright/skupper-vocab/blob/master/doc.adoc[Content]
|

|===
